sftp-source:
  directory: "/data/PROD/IN/"
  host: "185.112.228.25"
  port: "22"
  user: "wayfair"
  password: "lcV2WZYm"
ftp-target:
  directory: "/interfaces/EDI/DGB/WAYFAIR/IN/"
  host: "smb://172.20.42.3"
  port: "445"
  user: "EU-SVC0275"
  password: "s@4Nafebpb"