sftp-source:
  directory: "/data/PREP/IN/"
  host: "localhost"
  port: "22"
  user: "josif"
  password: "josif"
ftp-target:
  directory: "/myproject/"
  host: "smb://192.168.178.22"
  port: "445"
  user: "josif-cifs"
  password: "josif"
app:
 path: "C:/Users/Devoteam/AnypointStudio/studio-workspace/error-files-transfers/src/main/resources/web" 